#
# Copyright (c) 2023 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Publish Crate

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'libosdp-sys-v*'
    - 'libosdp-v*'
    - 'osdpctl-v*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag'
        required: true

jobs:
  cross_platform_check:
    name: Build libosdp_sys on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: cargo build -p libosdp_sys

  publish:
    needs: [cross_platform_check]
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: cargo publish --token ${CRATES_TOKEN} -p $(echo ${REL_TAG} | perl -pe 's/([a-z\-]+)-v.*/\1/')
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        REL_TAG: ${{ github.ref_name }}
