#
# Copyright (c) 2023 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Publish Crate

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'libosdp-sys-v*'
    - 'libosdp-v*'
    - 'osdpctl-v*'

jobs:
  publish:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: cargo publish --token ${CRATES_TOKEN} -p $(echo ${REL_TAG} | perl -pe 's/([a-z\-]+)-v.*/\1/')
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        REL_TAG: ${{ github.ref_name }}
