#
# Copyright (c) 2024 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

name: Publish libosdp

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'libosdp-sys-v*'
    - 'libosdp-v*'

jobs:
  cross_platform_check:
    name: Build libosdp on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - run: cargo build -p libosdp-sys

  publish:
    name: Publish Crate
    needs: [cross_platform_check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: "Setup environment - trigger"
      if: github.ref == 'refs/heads/master'
      run: echo "TAG=${TRIGGER_TAG}" >> "${GITHUB_ENV}"
      env:
        TRIGGER_TAG: ${{ github.event.inputs.tag }}
    - name: "Setup environment - tag"
      if: github.ref != 'refs/heads/master'
      run: echo "TAG=${REL_TAG}" >> "${GITHUB_ENV}"
      env:
        REL_TAG: ${{ github.ref_name }}
    - name: "Publish crate"
      run: |
        cargo publish --token ${CRATES_TOKEN} -p $(echo ${TAG} | perl -pe 's/([a-z\-]+)-v.*/\1/')
      env:
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
